### ISSUE TITLE
It works!!!

### ISSUE THREAD

**Issue by amazinigmech2418** [corescript-lang/Lang-base#1]
We just need some syntax updates and corescript 2.0 will be ready!

**Comment by redmangospros** [comment]
What Is Thus?

**Comment by amazinigmech2418** [comment]
The base for 2.0

**Comment by Pufflegamerz** [comment]
What's a base?

**Comment by amazinigmech2418** [comment]
For CoreScript 2.0. It is the base for it.

**Comment by Pufflegamerz** [comment]
I though we already had the editor.

**Comment by amazinigmech2418** [comment]
We do. This is for the future 2.0. Scratch 2 isn't the same as 1.4.

**Comment by Pufflegamerz** [comment]
I though we were going to add on to https://corescript-lang.github.io/editor/, not make a whole new one.

**Comment by Pufflegamerz** [comment]
For now, we will update https://github.com/corescript-lang/editor. We can use your code if we need a new editor.

**Comment by amazinigmech2418** [comment]
@Pufflegamerz This will be to improve the code for reading other code so it will be easier to make new commands. It won't be a completely different editor.
